# _config.yml
title: MDAP Internship Showcase

defaults:
  - scope:
      path: "interns"
    values:
      layout: intern
  - scope:
      path: "cohorts"
    values:
      layout: cohort

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github/
  - .ruby-version
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby